name: Discord Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"✅ GitHub ActionsからDiscord通知テスト成功"}' \
          "$DISCORD_WEBHOOK"
